apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: {{ include "<CHARTNAME>.name" . }}
  annotations:
    {{- toYaml .Values.serviceannotations | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key,$value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "<CHARTNAME>.selectorLabels" . | nindent 4 }}
